import{S as g,a as b,i as d}from"./assets/vendor-95dc692e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function l(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=l(t);fetch(t.href,r)}})();const S=document.querySelector(".gallery");document.querySelector(".form");function y(s){const e=s.map(o=>`<div class="card">
        <a class="gallery-link" href="${o.largeImageURL}">
            <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
          </a>
          <ul class="list">
            <li class="item">Likes: <span>${o.likes}</span></li>
            <li class="item">Views: <span>${o.views}</span></li>
            <li class="item">Comments: <span>${o.comments}</span></li>
            <li class="item">Downloads: <span>${o.downloads}</span></li>
          </ul>
          </div>`).join("");S.insertAdjacentHTML("beforeend",e),new g(".gallery a").refresh()}let p=15;const c=document.querySelector(".load");document.querySelector(".searchButton");document.querySelector(".search");const a=document.querySelector(".loader");debugger;async function h(){const s=`https://pixabay.com/api/?key=42766573-a347fa67a5b7233d1286bfaa7&q=${u}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${p}&page=${n}`;if(u)try{const e=await b.get(s);return e.data.hits.length===0?(a.style.display="none",c.style.display="none"):e.data.totalHits<p?(a.style.display="flex",y(e.data.hits),c.style.display="none",a.style.display="none",d.error({color:"blue",message:":x: We're sorry, but you've reached the end of search results.",position:"topRight"})):(a.style.display="flex",y(e.data.hits),c.style.display="block",a.style.display="none"),e.data}catch(e){console.log(e)}}document.querySelector(".searchButton");document.querySelector(".search");const q=document.querySelector(".gallery"),m=document.querySelector(".form");document.querySelector(".loader");const f=document.querySelector(".load");let n=1,w=15,u="";new g(".gallery a",{captionDelay:250,captionsData:"alt"});debugger;m.addEventListener("submit",async function(s){s.preventDefault(),n=1,q.innerHTML="",u=s.target.elements.searchImages.value;try{const e=await h();n+=1;const{height:l}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:l*2,behavior:"smooth"})}catch{d.error({color:"red",message:":x: Sorry, there was a mistake. Please try again!",position:"topRight"})}m.reset()});f.addEventListener("click",async function(s){s.preventDefault();try{const e=await h();if(n+=1,n>e.totalHits/w)return f.style.display="none",d.error({color:"blue",message:":x: We're sorry, but you've reached the end of search results.",position:"topRight"});const{height:l}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:l*2,behavior:"smooth"})}catch(e){console.log(e)}});
//# sourceMappingURL=commonHelpers.js.map
