import{S as g,a as S,i as u}from"./assets/vendor-95dc692e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const q=document.querySelector(".gallery");document.querySelector(".form");function y(s){const e=s.map(r=>`<div class="card">
        <a class="gallery-link" href="${r.largeImageURL}">
            <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
          </a>
          <ul class="list">
            <li class="item">Likes: <span>${r.likes}</span></li>
            <li class="item">Views: <span>${r.views}</span></li>
            <li class="item">Comments: <span>${r.comments}</span></li>
            <li class="item">Downloads: <span>${r.downloads}</span></li>
          </ul>
          </div>`).join("");q.insertAdjacentHTML("beforeend",e),new g(".gallery a").refresh()}let p=15;const m=document.querySelector(".load");document.querySelector(".searchButton");document.querySelector(".search");const f=document.querySelector(".loader");debugger;async function b(){const s=`https://pixabay.com/api/?key=42766573-a347fa67a5b7233d1286bfaa7&q=${d}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${p}&page=${n}`;if(d)try{const e=await S.get(s);return e.data.hits.length===0?(f.style.display="none",m.style.display="none"):e.data.totalHits<p?(y(e.data.hits),m.style.display="none",f.style.display="none",u.error({color:"blue",message:":x: We're sorry, but you've reached the end of search results.",position:"topRight"})):y(e.data.hits),e.data}catch(e){console.log(e)}}document.querySelector(".searchButton");document.querySelector(".search");const w=document.querySelector(".gallery"),h=document.querySelector(".form"),i=document.querySelector(".loader"),l=document.querySelector(".load");let n=1,v=15,d="";new g(".gallery a",{captionDelay:250,captionsData:"alt"});h.addEventListener("submit",async function(s){s.preventDefault(),n=1,l.style.display="none",i.style.display="flex",w.innerHTML="",d=s.target.elements.searchImages.value;try{const e=await b();n+=1,l.style.display="block";const{height:a}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch{l.style.display="none",u.error({color:"red",message:":x: Sorry, there was a mistake. Please try again!",position:"topRight"})}finally{i.style.display="none"}h.reset()});l.addEventListener("click",async function(s){s.preventDefault(),l.style.display="none",i.style.display="flex";try{const e=await b();if(n+=1,n>e.totalHits/v)return l.style.display="none",u.error({color:"blue",message:":x: We're sorry, but you've reached the end of search results.",position:"topRight"});l.style.display="block";const{height:a}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch(e){console.log(e)}finally{i.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
