import{S as m,a as S,i as f}from"./assets/vendor-95dc692e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function l(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=l(t);fetch(t.href,r)}})();const b=document.querySelector(".gallery");document.querySelector(".form");function q(s){const e=s.map(o=>`<div class="card">
        <a class="gallery-link" href="${o.largeImageURL}">
            <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
          </a>
          <ul class="list">
            <li class="item">Likes: <span>${o.likes}</span></li>
            <li class="item">Views: <span>${o.views}</span></li>
            <li class="item">Comments: <span>${o.comments}</span></li>
            <li class="item">Downloads: <span>${o.downloads}</span></li>
          </ul>
          </div>`).join("");b.insertAdjacentHTML("beforeend",e),new m(".gallery a").refresh()}const d=document.querySelector(".load");document.querySelector(".searchButton");document.querySelector(".search");const y=document.querySelector(".loader");async function g(){const s=`https://pixabay.com/api/?key=42766573-a347fa67a5b7233d1286bfaa7&q=${u}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${h}&page=${a}`;debugger;if(u)try{const e=await S.get(s);return e.data.hits.length===0?(y.style.display="none",d.style.display="none"):(q(e.data.hits),y.style.display="none",d.style.display="block"),e.data}catch(e){console.log(e)}}document.querySelector(".searchButton");document.querySelector(".search");const w=document.querySelector(".gallery"),p=document.querySelector(".form"),i=document.querySelector(".loader"),c=document.querySelector(".load");let a=1,h=3,u="";new m(".gallery a",{captionDelay:250,captionsData:"alt"});p.addEventListener("submit",async function(s){s.preventDefault(),a=1,i.style.display="flex",w.innerHTML="",u=s.target.elements.searchImages.value;try{const e=await g();a+=1;const{height:l}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:l*2,behavior:"smooth"})}catch{f.error({color:"red",message:":x: Sorry, there was a mistake. Please try again!",position:"topRight"})}p.reset()});c.addEventListener("click",async function(s){s.preventDefault(),i.style.display="flex",c.style.display="none";try{const e=await g();if(a+=1,i.style.display="none",a>e.totalHits/h)return c.style.display="none",f.error({color:"blue",message:":x: We're sorry, but you've reached the end of search results.",position:"topRight"});const{height:l}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:l*2,behavior:"smooth"})}catch(e){console.log(e)}});
//# sourceMappingURL=commonHelpers.js.map
